server: 
  port: 9527

spring:  application:    name: study-springcloud-zuul-gateway
eureka: 
  client:    service-url:      defaultZone: http://localhost:8761/eureka/
  instance:    instance-id: gateway-9527.com
    prefer-ip-address: true

zuul:
  ignored-services: study-springcloud-provider
  routes:                                               mydept.serviceId: study-springcloud-provider    
    mydept.path: /mydept/**                         
    
info:
  app.name: study-springcloud
  company.name: www.tingyu.com
  build.artifactId: study-springcloud-zuul-gateway-9527
  build.version: 0.0.1-SNAPSHOT